# This rule is not used by the project reliableapp-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ebay.training.ebay.training.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: reliableapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: reliableapp-editor-role
rules:
- apiGroups:
  - ebay.training.ebay.training
  resources:
  - reliableapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ebay.training.ebay.training
  resources:
  - reliableapps/status
  verbs:
  - get
