apiVersion: ebay.training/v1
kind: ReliableApp
metadata:
  labels:
    app.kubernetes.io/name: reliableapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: reliableapp-sample
spec:
  # TODO(user): Add fields here
